#!/bin/bash
# A full setup script

# install command line tools:
xcode-select --install

# some can't-live-without macos settings:

# Faster mouse movement
defaults write -g com.apple.trackpad.scaling 3

# Disable “natural” (Lion-style) scrolling
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

# homebrew
if which brew; then
    echo " Installed: homebrew"
else
    echo "Installing: homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# 1pass
if [ -d "/Applications/1Password 7.app" ]; then
    echo " Installed: 1Password"
else
    echo "Installing: 1Password..."
    brew install 1password
fi

# github config (for cloning dotfiles)
if [ -d "$HOME/.ssh" ]; then
    echo "     Setup: github"
else
    echo "Setting up: github"
    echo " - New ssh key; enter email: "
    read email
    ssh-keygen -t ed25519 -C $email

    eval "$(ssh-agent -s)"

    mkdir -p $HOME/.ssh
    cat >$HOME/.ssh/config <<EOL
Host *
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519
EOL

    ssh-add -K $HOME/.ssh/id_ed25519
    pbcopy < $HOME/.ssh/id_ed25519.pub

    echo " - Public key copied to clipboard; opening github to add..."
    open https://github.com/settings/keys

    read -p " - Press enter to continue"
fi

# oh-my-zsh *first* (since it overwrites a personal .zshrc)
if [ -d "$HOME/.oh-my-zsh" ]; then
    echo " Installed: oh-my-zsh"
else
    echo "Installing: oh-my-zsh..."
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# dotfiles, finally
if [ -d "$HOME/.dotfiles" ]; then
    echo " Installed: dotfiles"
else
    echo "Installing: personal dotfiles..."

    git clone git@github.com:dhleong/dotfiler.git $HOME/.dotfiles
    $HOME/.dotfiles/bin/dot add git@github.com:dhleong/dots.git
    $HOME/.dotfiles/bin/dot update
fi

# a few more apps to get started:
echo "Installing: (various tools)..."
brew install --cask bettertouchtool macvim iterm2
brew install the_silver_searcher fzf hub zsh-completions

echo "Done!"
echo ' - You may need to logout and back in for some settings to update'
echo ' - Remap capslock to escape by hand... not sure how to automate'
echo ' - Brewfile can be loaded by running `brew bundle` in ~/.dotfiles'
