#!/bin/bash
# A full setup script

is_mac() {
    [[ "$OSTYPE" == "darwin"* ]]
}

ensure_cask() {
    dotAppName=$1
    brewName=$2

    if ! is_mac; then
        return
    fi

    if [ -d "/Applications/$dotAppName.app" ]; then
        echo " Installed: $dotAppName"
    else
        echo "Installing: $dotAppName (cask $brewName)..."
        brew install --cask $brewName
    fi
}

has_cli() {
    which $1 > /dev/null
}

has_nix() {
    which nix-env > /dev/null
}

if is_mac; then

    # install command line tools:
    xcode-select --install

    # some can't-live-without macos settings:

    # Faster mouse movement
    defaults write -g com.apple.trackpad.scaling 3

    # Disable “natural” (Lion-style) scrolling
    defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

    # homebrew
    if has_cli brew; then
        echo " Installed: homebrew"
    else
        echo "Installing: homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    # 1pass (needed to authenticate with github)
    ensure_cask "1Password 7" "1password"

fi

# github config (for cloning dotfiles)
if [ -d "$HOME/.ssh" ]; then
    echo "     Setup: github"
elif is_mac; then
    echo "Setting up: github"
    echo " - New ssh key; enter email: "
    read email
    ssh-keygen -t ed25519 -C $email

    eval "$(ssh-agent -s)"

    mkdir -p $HOME/.ssh
    cat >$HOME/.ssh/config <<EOL
Host *
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519
EOL

    ssh-add -K $HOME/.ssh/id_ed25519
    pbcopy < $HOME/.ssh/id_ed25519.pub

    echo " - Public key copied to clipboard; opening github to add..."
    open https://github.com/settings/keys

    read -p " - Press enter to continue"
fi

# dotfiles, finally
if [ -d "$HOME/.dotfiles" ]; then
    echo " Installed: dotfiles"
else
    echo "Installing: personal dotfiles..."

    # create these before updating dots, so dotfiler doesn't cause all
    # local-specific config to try to go into our dots repo
    mkdir $HOME/.config
    mkdir $HOME/.zsh

    git clone git@github.com:dhleong/dotfiler.git $HOME/.dotfiles
    $HOME/.dotfiles/bin/dot add git@github.com:dhleong/dots.git
    $HOME/.dotfiles/bin/dot update
fi

# oh-my-zsh, making sure not to overwrite the local zshrc
if [ -d "$HOME/.oh-my-zsh" ]; then
    echo " Installed: oh-my-zsh"
else
    echo "Installing: oh-my-zsh..."
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc
fi

# fonts
if [ -f "$HOME/Library/Fonts/Inconsolata for Powerline.otf" ]; then
    echo " Installed: Inconsolata font"
elif is_mac; then
    echo "Installing: Inconsolata font..."
    curl "https://raw.githubusercontent.com/powerline/fonts/master/Inconsolata/Inconsolata%20for%20Powerline.otf" \
        -o "$HOME/Library/Fonts/Inconsolata for Powerline.otf"

    # open to ensure it's available
    open "$HOME/Library/Fonts/Inconsolata for Powerline.otf"
fi

# iterm2 shell integration
if [ -f "$HOME/.iterm2_shell_integration" ]; then
    echo " Installed: iTerm2 shell integration"
elif is_mac; then
    echo "Installing: iTerm2 shell integration"
    curl -L https://iterm2.com/shell_integration/zsh \ 
        -o ~/.iterm2_shell_integration.zsh
fi

# a few more apps to get started:
ensure_cask "MacVim" "macvim"
ensure_cask "BetterTouchTool" "bettertouchtool"
ensure_cask "iTerm" "iterm2"

if has_cli cmake; then
    echo " Installed: build tools (for YCM)"
elif is_mac; then
    echo "Installing: build tools (for YCM)"
    brew install cmake python mono go nodejs
else
    echo "NOT Installing: build tools (for YCM)"
fi

if has_cli gh && has_cli hub; then
    echo " Installed: github cli"
elif is_mac; then
    echo "Installing: github cli..."
    brew install gh hub
else
    echo "NOT Installing: github cli"
fi

if has_cli rg && has_cli fzf; then
    echo " Installed: (various tools)"
elif is_mac; then
    echo "Installing: (various tools)..."
    brew install ripgrep fzf zsh-completions
elif has_nix; then
    echo "Installing: (various tools)..."
    nix-env -i ripgrep -i fzf -i zsh-completions
else
    echo "NOT Installing: (various tools)"
fi

echo "Done!"
echo ' - You may need to logout and back in for some settings to update'
echo ' - gh and hub are not setup automatically'

if is_mac; then
    echo ' - Remap capslock to escape by hand... not sure how to automate'
    echo ' - Brewfile can be loaded by running `brew bundle` in ~/.dotfiles'
fi
